name: CI

on: [ pull_request ]

jobs:
  host_normal:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py host_toolchain

  host_normal_windows_symlinks:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py host_toolchain --extra_args windows_enable_symlinks

  host_nolegacy_runfiles:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py host_toolchain --extra_args nolegacy_external_runfiles

  host_non_hermetic:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py host_toolchain --extra_args spawn_strategy=local

  toolchain_normal:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py hermetic_toolchain

  toolchain_windows_symlinks:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py hermetic_toolchain --extra_args windows_enable_symlinks

  toolchain_nolegacy_runfiles:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py hermetic_toolchain --extra_args nolegacy_external_runfiles

  toolchain_non_hermetic:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py hermetic_toolchain --extra_args spawn_strategy=local

  toolchain_nolegacy_runfile_non_hermetic:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: python run_benchmark.py hermetic_toolchain --extra_args nolegacy_external_runfiles spawn_strategy=local
