name: CI

on: [ pull_request ]

jobs:
  host_normal:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd host_toolchain
          bazel test //...
          echo -e "\nSecond Run\n"
          bazel test --nocache_test_results //...

  host_nolegacy_runfiles:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd host_toolchain
          bazel test --nolegacy_external_runfiles //...
          echo -e "\nSecond Run\n"
          bazel test --nocache_test_results --nolegacy_external_runfiles //...

  host_non_hermetic:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd host_toolchain
          bazel test --spawn_strategy=local //...
          echo -e "\nSecond Run\n"
          bazel test --nocache_test_results --spawn_strategy=local //...

  toolchain_normal:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test //...
          echo -e "\nSecond Run\n"
          bazel test --nocache_test_results //...

  toolchain_nolegacy_runfiles:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test --nolegacy_external_runfiles //...
          echo -e "\nSecond Run\n"
          bazel test --nocache_test_results --nolegacy_external_runfiles //...

  toolchain_non_hermetic:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test --spawn_strategy=local //...
          echo -e "\nSecond Run\n"
          bazel test --nocache_test_results --spawn_strategy=local //...

  toolchain_nolegacy_runfile_non_hermetic:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test --nolegacy_external_runfiles --spawn_strategy=local //...
          echo -e "\nSecond Run\n"
          bazel test --nocache_test_results --nolegacy_external_runfiles --spawn_strategy=local //...
