name: CI

on: [ pull_request ]

jobs:
  host_normal:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd host_toolchain
          bazel test //...
          bazel test --nocache_test_results //...

  host_nolegacy_runfiles:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd host_toolchain
          bazel test --nolegacy_external_runfiles //...
          bazel test --nocache_test_results --nolegacy_external_runfiles //...

  host_non_hermetic:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd host_toolchain
          bazel test --spawn_strategy=local //...
          bazel test --nocache_test_results --spawn_strategy=local //...

  toolchain_normal:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test //...
          bazel test --nocache_test_results //...

  toolchain_nolegacy_runfiles:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test --nolegacy_external_runfiles //...
          bazel test --nocache_test_results --nolegacy_external_runfiles //...

  toolchain_non_hermetic:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test --spawn_strategy=local //...
          bazel test --nocache_test_results --spawn_strategy=local //...

  toolchain_nolegacy_runfile_non_hermetic:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build examples
        run: |
          cd hermetic_toolchain
          bazel test --nolegacy_external_runfiles --spawn_strategy=local //...
          bazel test --nocache_test_results --nolegacy_external_runfiles --spawn_strategy=local //...
